name: Deploy to GKE

on:
  workflow_dispatch:
#  push:
#    tags:
#      - 'releases/v*'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: complex-cluster
  GKE_ZONE: us-central1-c

jobs:
  setup-build-publish-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get a version from a tag ref
        id: vars
        run: |-
          tagRef=${{ github.ref }}
          version=${tagRef#'refs/tags/releases/'}
          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get the GKE credentials
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Apply changes to GKE
        run: |-
          ./kustomize edit set image grszyman/complex-api=grszyman/complex-api:${{ steps.vars.outputs.version }}
          ./kustomize edit set image grszyman/complex-client=grszyman/complex-client:${{ steps.vars.outputs.version }}
          ./kustomize edit set image grszyman/complex-worker=grszyman/complex-worker:${{ steps.vars.outputs.version }}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/api-deployment
          kubectl rollout status deployment/client-deployment
          kubectl rollout status deployment/worker-deployment
          kubectl get services -o wide
