name: Pipeline
on:
  push:
    branches: 
      - '**'
    tags-ignore: 
      - 'releases/v*'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build tests
        run: docker build -t grszyman/docker-client-dev -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true grszyman/docker-client-dev npm test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # without REPOSITORY_TOKEN, pushing a tag wouldn't trigger other workflows
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}

      - name: Set short git commit SHA
        id: vars
        run:
          echo "version=v1.0.0-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Build client
        run: docker build -t grszyman/complex-client -t grszyman/complex-client:${{ steps.vars.outputs.version }} ./client

      - name: Push client
        run: docker push -a grszyman/complex-client

      - name: Build api
        run: docker build -t grszyman/complex-api -t grszyman/complex-api:${{ steps.vars.outputs.version }} ./api

      - name: Push api
        run: docker push -a grszyman/complex-api

      - name: Build worker
        run: docker build -t grszyman/complex-worker -t grszyman/complex-worker:${{ steps.vars.outputs.version }} ./worker

      - name: Push worker
        run: docker push -a grszyman/complex-worker

      # TODO: https://docs.github.com/en/repositories/releasing-projects-on-github/automation-for-release-forms-with-query-parameters
      - name: Tag a released version
        run: |-
          git tag releases/${{ steps.vars.outputs.version }}
          git push origin releases/${{ steps.vars.outputs.version }}        

    outputs:
      version: ${{ steps.vars.outputs.version }}
